// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: drive.proto

module scylla.drive.drive;

import google.protobuf;
import scylla.zone.zone;

enum protocVersion = 3006001;

class DriveAction
{
    @Proto(1) Action action = protoDefaultValue!Action;
    @Proto(2) ResourceIdentifier drive = protoDefaultValue!ResourceIdentifier;

    enum Action
    {
        ATTACH = 0,
        DETACH = 1,
    }
}

class DriveUpdateAction
{
    @Proto(1) ResourceIdentifier id = protoDefaultValue!ResourceIdentifier;
    @Proto(2) Drive update = protoDefaultValue!Drive;
}

class DriveReply
{
    @Proto(1) int code = protoDefaultValue!int;
    @Proto(2) string info = protoDefaultValue!string;
}

class Drive
{
    @Proto(1) string driveId = protoDefaultValue!string;
    @Proto(2) long size = protoDefaultValue!long;
    @Proto(3) bool isRootDevice = protoDefaultValue!bool;
    @Proto(4) bool isReadOnly = protoDefaultValue!bool;
    @Proto(5) string template_ = protoDefaultValue!string;
}
