// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zone.proto

module scylla.zone.zone;

import google.protobuf;

enum protocVersion = 3006001;

class ResourceIdentifier
{
    @Proto(1) ZoneIdentifier zone = protoDefaultValue!ZoneIdentifier;
    @Proto(2) string uuid = protoDefaultValue!string;
}

class ZoneIdentifier
{
    @Proto(1) string zoneId = protoDefaultValue!string;
}

class Zone
{
    @Proto(1) string location = protoDefaultValue!string;
    @Proto(2) string name = protoDefaultValue!string;
}

class Empty
{
}
