// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: node.proto

module scylla.node.node;

import google.protobuf;
import scylla.instance.instance;
import scylla.zone.zone;
import scylla.drive.drive;
import scylla.nic.nic;

enum protocVersion = 3006001;

class DestroyReply
{
    @Proto(1) int code = protoDefaultValue!int;
    @Proto(2) string info = protoDefaultValue!string;
}

class ResourceStatus
{
    @Proto(1) string status = protoDefaultValue!string;
    @Proto(2) string messageClass = protoDefaultValue!string;
}

class ResourceReply
{
    @Proto(1) bool canHandle = protoDefaultValue!bool;
    @Proto(2) int currentVmCount = protoDefaultValue!int;
    @Proto(3) int allocatedVcpus = protoDefaultValue!int;
    @Proto(4) int maxVcpus = protoDefaultValue!int;
    @Proto(5) long allocatedRam = protoDefaultValue!long;
    @Proto(6) long maxRam = protoDefaultValue!long;
}

class LogEntry
{
    @Proto(1) long timestamp = protoDefaultValue!long;
    @Proto(2) string entry = protoDefaultValue!string;
    @Proto(3) string origin = protoDefaultValue!string;
}

class InstanceLog
{
    @Proto(1) LogEntry[] log = protoDefaultValue!(LogEntry[]);
}

class BillableUnit
{
    @Proto(1) int hourlyRate = protoDefaultValue!int;
    @Proto(2) long used = protoDefaultValue!long;
    @Proto(3) ResourceIdentifier resource = protoDefaultValue!ResourceIdentifier;
}

class AssociationReply
{
    @Proto(1) int code = protoDefaultValue!int;
    @Proto(2) string reply = protoDefaultValue!string;
}

class AssociationInfo
{
    @Proto(1) ResourceIdentifier resource = protoDefaultValue!ResourceIdentifier;
    @Proto(2) ResourceIdentifier target = protoDefaultValue!ResourceIdentifier;
}
