// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nic.proto

module scylla.nic.nic;

import google.protobuf;
import scylla.zone.zone;

enum protocVersion = 3006001;

class NICReply
{
    @Proto(1) int code = protoDefaultValue!int;
    @Proto(2) string info = protoDefaultValue!string;
}

class NICAction
{
    @Proto(1) Action action = protoDefaultValue!Action;
    @Proto(2) ResourceIdentifier nic = protoDefaultValue!ResourceIdentifier;

    enum Action
    {
        DETACH = 0,
        ATTACH = 1,
    }
}

class SecPolUpdateAction
{
    @Proto(1) ResourceIdentifier id = protoDefaultValue!ResourceIdentifier;
    @Proto(2) SecurityPolicy secpol = protoDefaultValue!SecurityPolicy;
}

class SecurityInPolicy
{
    @Proto(1) string name = protoDefaultValue!string;
    @Proto(2) string incomingIpRange = protoDefaultValue!string;
    @Proto(3) string incomingPortRange = protoDefaultValue!string;
    @Proto(4) string outgoingPortRange = protoDefaultValue!string;
    @Proto(5) SecStatus status = protoDefaultValue!SecStatus;
}

class SecurityOutPolicy
{
    @Proto(1) string name = protoDefaultValue!string;
    @Proto(2) string incomingPortRange = protoDefaultValue!string;
    @Proto(3) string outgoingIpRange = protoDefaultValue!string;
    @Proto(4) string outgoingPortRange = protoDefaultValue!string;
    @Proto(5) SecStatus status = protoDefaultValue!SecStatus;
}

class SecurityPolicy
{
    @Proto(1) SecurityInPolicy[] ingress = protoDefaultValue!(SecurityInPolicy[]);
    @Proto(2) SecurityOutPolicy[] egress = protoDefaultValue!(SecurityOutPolicy[]);
}

class NetworkInterface
{
    @Proto(1) string publicIp = protoDefaultValue!string;
    @Proto(2) string privateIp = protoDefaultValue!string;
    @Proto(3) SecurityPolicy secpol = protoDefaultValue!SecurityPolicy;
}

enum SecStatus
{
    DENY = 0,
    ALLOW = 1,
}
