name: CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: WebFreak001/setup-dmd@v1
      with:
        dmd-version: 2.088.0
    - name: Pull protod
      run: |
        git clone https://github.com/dcarp/protobuf-d.git
        cd protobuf-d/protoc_gen_d
        dub build
        cd ..
        ls build/
        sudo cp build/protoc-gen-d /usr/bin/
    - name: Add the library and build it
      run: dub add-local library/
    - name: Build the Orchestrator
      run: dub build -c orchestrator
    - name: Build the VMM
      run: dub build -c vmm
    - name: Build the client executable
      run: dub build -c cli
      
