name: CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Pull dub
      run: |
        curl -fsS https://dlang.org/install.sh | bash -s dmd
        sudo apt-get install dub
    - name: Pull protod
      run: |
        git clone https://github.com/dcarp/protobuf-d.git
        cd protobuf-d/protoc_gen_d
        dub build
        cd ..
        ls build/
        sudo cp build/protoc-gen-d /usr/bin/
    - name: Add the library and build it
      run: dub add-local library/
      
